/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:f8cb40b9-a4b1-4eca-a2e2-ab4fabd62456",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_AOSIQf4X0",
  aws_user_pools_web_client_id: "1f0uffego44nt3l7fkoc1anm60",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_user_files_s3_bucket: "installer-update-bucket141259-dev",
  aws_user_files_s3_bucket_region: "us-east-1",
};

export default awsmobile;
